CREATE TABLE Patient
(
  First_Name VARCHAR(100) NOT NULL,
  Last_Name VARCHAR(100) NOT NULL,
  PID INT Primary Key GENERATED BY DEFAULT AS IDENTITY,
  Age INT NOT NULL,
  Blood_Pressure_ VARCHAR(25),
  Blood_Sugar_Level FLOAT,
  Blood_Type CHAR(5),
  Email VARCHAR(100) UNIQUE NOT NULL,
  Password VARCHAR(100) NOT NULL,
  Health_Insurance VARCHAR(100) ,
  Photo VARCHAR(300)
);

CREATE TABLE Doctor
(
  First_Name VARCHAR(100) NOT NULL,
  Last_Name VARCHAR(100) NOT NULL,
  Age INT NOT NULL,
  DID INT GENERATED By DEFAULT as identity ,
  Email VARCHAR(100) NOT NULL,
  Password VARCHAR(100) NOT NULL,
  Position VARCHAR(100) NOT NULL,
  Photo VARCHAR(300),
  PRIMARY KEY (DID),
  UNIQUE (Email)
);

CREATE TABLE Admin
(
  First_Name VARCHAR(100) NOT NULL,
  Last_Name VARCHAR(100) NOT NULL,
  Age INT NOT NULL,
  AID INT GENERATED by default as identity,
  Email VARCHAR(100) NOT NULL,
  Password VARCHAR(100) NOT NULL,
  PRIMARY KEY (AID),
  UNIQUE (Email)
);

CREATE TABLE Appointment
(
  Date DATE default current_date,
  Status VARCHAR(25) NOT NULL,
  Time Time default current_time,
  AppID INT GENERATED by default as identity ,
  PID INT NOT NULL,
  DID INT NOT NULL,
  PRIMARY KEY (AppID),
  FOREIGN KEY (PID) REFERENCES Patient(PID),
  FOREIGN KEY (DID) REFERENCES Doctor(DID)
);

CREATE TABLE Messages
(
  Sender VARCHAR(100) NOT NULL,
  Receiver VARCHAR(100) NOT NULL,
  Content VARCHAR(500) NOT NULL,
  Date DATE default current_date,
  Time Time default current_time,
  Message_ID INT GENERATED by default as identity,
  DID INT NOT NULL,
  PID INT NOT NULL,
  PRIMARY KEY (Message_ID),
  FOREIGN KEY (DID) REFERENCES Doctor(DID),
  FOREIGN KEY (PID) REFERENCES Patient(PID)
);

CREATE TABLE Report
(
  Prescription VARCHAR(300) NOT NULL,
  Report_ID INT GENERATED by default as identity,
  DID INT NOT NULL,
  PID INT NOT NULL,
  PRIMARY KEY (Report_ID),
  FOREIGN KEY (DID) REFERENCES Doctor(DID),
  FOREIGN KEY (PID) REFERENCES Patient(PID)
);

CREATE TABLE Patient_Phone_Numbers
(
  Phone_Numbers VARCHAR(25) NOT NULL,
  PID INT NOT NULL,
  PRIMARY KEY (Phone_Numbers, PID),
  FOREIGN KEY (PID) REFERENCES Patient(PID)
);

CREATE TABLE Doctor_Phone_Numbers
(
  Phone_Numbers VARCHAR(25) NOT NULL,
  DID INT NOT NULL,
  PRIMARY KEY (Phone_Numbers, DID),
  FOREIGN KEY (DID) REFERENCES Doctor(DID)
);

CREATE TABLE Admin_Phone_Number
(
  Phone_Number VARCHAR(25) NOT NULL,
  AID INT NOT NULL,
  PRIMARY KEY (Phone_Number, AID),
  FOREIGN KEY (AID) REFERENCES Admin(AID)
);

CREATE TABLE Report_Scans
(
  Scans VARCHAR(300) ,
  Report_ID INT NOT NULL,
  PRIMARY KEY (Scans, Report_ID),
  FOREIGN KEY (Report_ID) REFERENCES Report(Report_ID)
);